server:
  port: 8083
spring:
  application:
    name: Asset Elastic Service
  output:
    ansi:
      enabled: always
  elasticsearch:
    uris: https://4e676d46e34e40cebed51ac817b28782.us-central1.gcp.cloud.es.io:443
    username: elastic
    password: qT4CXu7kMZhk4L4TNxKxW84N
