server:
  port: 8084
  error:
    include-stacktrace: never
spring:
  application:
    name: User Service
  output:
    ansi:
      enabled: always
  neo4j:
    uri: neo4j+s://3ad2a5fe.databases.neo4j.io
    authentication:
      username: neo4j
      password: nhatprola1
# eureka:
#   client:
#     service-url:
#       defaultZone: http://localhost:8761/eureka/
