server:
  port: 8082
spring:
  application:
    name: Asset Service
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:postgresql://localhost:5432/asset
    username: ltn2412
    password: nhatprola1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: author-group
      auto-offset-reset: earliest
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # properties:
      #   "[spring.json.type.mapping]": message:com.asset.asset_service.model.dto.kafka.KafkaMessage
# eureka:
#   client:
#     serviceUrl:
#       defaultZone: http://localhost:8761/eureka/
# logging:
#   file:
#     name: asset.log
#   level:
#     root: info
